steps:
  #########################################
  # Extract source files from README.org  #
  #########################################
  - name: debian
    entrypoint: bash
    args:
      - -c
      - |
        apt update  -y
        apt install -y emacs-nox
        emacs -Q --batch --script tangle.el
    id: tangle-sources

  ###################################
  # Create a tarball of the sources #
  ###################################
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        tar cvf sources.tar hcb-backend hcb-frontend hcb-data-import hcb-setup-database setup.sh cleanup.sh
    id: make-source-tarball
    waitFor: ['tangle-sources']

artifacts:
  objects:
    location: 'gs://hcb-helsinki-city-bikes/$BRANCH_NAME/'
    paths: ['sources.tar']
